import {
  baptisteImg,
  baptistetwoImg,
  baptistethreeImg,
  baptistefourImg,
  barryImg,
  barrytwoImg,
  barrythreeImg,
  barryfourImg,
  bartImg,
  barttwoImg,
  bartthreeImg,
  bartfourImg,
  benImg,
  bentwoImg,
  benthreeImg,
  benfourImg,
  chrisImg,
  christwoImg,
  christhreeImg,
  chrisfourImg,
  craigImg,
  craigtwoImg,
  craigthreeImg,
  craigfourImg,
  emanuelImg,
  emanueltwoImg,
  emanuelthreeImg,
  emanuelfourImg,
  florentImg,
  florenttwoImg,
  florentthreeImg,
  florentfourImg,
  jensImg,
  jenstwoImg,
  jensthreeImg,
  jensfourImg,
  justinImg,
  justintwoImg,
  justinthreeImg,
  justinfourImg,
  lucasImg,
  lucastwoImg,
  lucasthreeImg,
  lucasfourImg,
  mattImg,
  matttwoImg,
  mattthreeImg,
  mattfourImg,
  mattiaImg,
  mattiatwoImg,
  mattiathreeImg,
  mattiafourImg,
  nikoImg,
  nikotwoImg,
  nikothreeImg,
  nikofourImg,
  nunoImg,
  nunotwoImg,
  nunothreeImg,
  nunofourImg,
  patImg,
  pattwoImg,
  patthreeImg,
  patfourImg,
  richImg,
  richtwoImg,
  richthreeImg,
  richfourImg,
} from "./image";

export const SliderData = [
  {
    name: "Baptiste",
    age: 29,
    id: 1,
    location: "Hamburg",
    image: [baptisteImg, baptistetwoImg, baptistethreeImg, baptistefourImg],
  },

  {
    name: "Barry",
    age: 34,
    id: 2,
    location: "Munich",
    image: [barryImg, barrytwoImg, barrythreeImg, barryfourImg],
  },

  {
    name: "Bart",
    age: 28,
    id: 3,
    location: "Hanover",
    image: [bartImg, barttwoImg, bartthreeImg, bartfourImg],
  },

  {
    name: "Ben",
    age: 25,
    id: 4,
    location: "London",
    image: [benImg, bentwoImg, benthreeImg, benfourImg],
  },

  {
    name: "Chris",
    age: 27,
    id: 5,
    location: "Manchester",
    image: [chrisImg, christwoImg, christhreeImg, chrisfourImg],
  },

  {
    name: "Craig",
    age: 26,
    id: 6,
    location: "Paris",
    image: [craigImg, craigtwoImg, craigthreeImg, craigfourImg],
  },

  {
    name: "Emanuel",
    age: 30,
    id: 7,
    location: "Milan",
    image: [emanuelImg, emanueltwoImg, emanuelthreeImg, emanuelfourImg],
  },

  {
    name: "Florent",
    age: 33,
    id: 8,
    location: "Paris",
    image: [florentImg, florenttwoImg, florentthreeImg, florentfourImg],
  },

  {
    name: "Jens",
    age: 29,
    id: 9,
    location: "Stockholm",
    image: [jensImg, jenstwoImg, jensthreeImg, jensfourImg],
  },

  {
    name: "Justin",
    age: 30,
    id: 10,
    location: "New York",
    image: [justinImg, justintwoImg, justinthreeImg, justinfourImg],
  },

  {
    name: "Lucas",
    age: 30,
    id: 11,
    location: "Lisbon",
    image: [lucasImg, lucastwoImg, lucasthreeImg, lucasfourImg],
  },

  {
    name: "Matt",
    age: 32,
    id: 12,
    location: "London",
    image: [mattImg, matttwoImg, mattthreeImg, mattfourImg],
  },

  {
    name: "Mattia",
    age: 27,
    id: 13,
    location: "Hamburg",
    image: [mattiaImg, mattiatwoImg, mattiathreeImg, mattiafourImg],
  },

  {
    name: "Niko",
    age: 35,
    id: 14,
    location: "Paris",
    image: [nikoImg, nikotwoImg, nikothreeImg, nikofourImg],
  },

  {
    name: "Nuno",
    age: 34,
    id: 15,
    location: "Madrid",
    image: [nunoImg, nunotwoImg, nunothreeImg, nunofourImg],
  },

  {
    name: "Pat",
    age: 34,
    id: 16,
    location: "Birmingham",
    image: [patImg, pattwoImg, patthreeImg, patfourImg],
  },

  {
    name: "Rich",
    age: 41,
    id: 18,
    location: "San Fransico",
    image: [richImg, richtwoImg, richthreeImg, richfourImg],
  },
];
